backend:
  name: git-gateway
  branch: dev
media_folder: "src/images/uploads"
public_folder: "/assets/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.hbs"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Date published", name: "datePublished", widget: "datetime"}
      - {label: "Featured image", name: "image", widget: "image"}
      - {label: "Featured image Alt text", name: "imageAlt", widget: "string"}
      - {label: "Featured image caption", name: "imageCap", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

